site: Zelenyy's Blog
title: Zelenyy's Blog
greetings: Pat's Blog
description: >-
  Welcome to my blog, filled with silly little thoughts and sillier littler personal projects!<br>

  I know, pretty empty at the moment but hopefully it'll look better once I write some stuff.

lang: en-US
timezone:  Australia/Sydney
repo: https://github.com/mrmelonson/zelenyy_blog # site repo [optional]
data-theme: light # default theme "dark" | "light"
#discus-identifier: zel # replace with your disqus shortname

author:
  name: Patrick Fennell
  bio: A 20yr computer science student studying at UTS
  userpicture: 
  username: Zelenyy
  github: https://github.com/mrmelonson
  twitter: https://twitter.com/Zelenyy_is_cool
  email: patrickfennell3@gmail.com # email adress
  linkedIn: https://www.linkedin.com/in/patrick-fennell-19a71016a/

# Font Settings
googlewebfonts: family=DM+Sans:wght@400;700&family=Fira+Code:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "http://zelenyy.info" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty 

# local
#url: "http://localhost:4000" # 
# baseurl: "" # 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  - deploy.sh
  - run.sh
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


